general:
  use_uvloop: true
  logging:
    console:
      _type: console
      level: INFO

  front_end:
    _type: fastapi

functions:
  current_datetime:
    _type: current_datetime

llms:
  nim_llm:
    _type: nim
    model_name: moonshotai/kimi-k2-instruct
    temperature: 0.0
    max_tokens: 2048
    api_key: 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

embedders:
  nim_embedder:
    _type: nim
    model_name: nvidia/nv-embedqa-e5-v5

workflow:
  _type: career_guide
  tool_names:
    - current_datetime
  llm_name: nim_llm
  embedder_name: nim_embedder
  max_history: 20
  personality: "mentor"  # Options: mentor, professional, casual
  search_engine: "bing"
  ingest_glob: "data/career_resources/*.{pdf,txt,docx,csv,xlsx}"
  description: "AI-Powered Career Guidance and Path Planning Assistant"
  chunk_size: 1024